export const stapleItems = [
    {
      name: "White Rice & Pasta (Dry)",
      category: "grains",
      shelfLifePantry: "1 - 2 Years",
      shelfLifeOpened: "1 Year",
      storageType: "Cool, Dark, Airtight Container",
      tips: "Keep away from moisture. Transfer from original bags to airtight glass or food-safe plastic containers to prevent pantry moths.",
      badge: "Long Shelf Life",
    },
    {
      name: "Brown Rice (Whole Grain)",
      category: "grains",
      shelfLifePantry: "6 Months",
      shelfLifeOpened: "3 - 6 Months",
      storageType: "Pantry or Refrigerator",
      tips: "Contains natural oils in the germ that can go rancid. Extend shelf life up to 1 year by storing in the fridge or freezer.",
      badge: "Perishable Grain",
    },
    {
      name: "Canned Beans & Vegetables",
      category: "canned",
      shelfLifePantry: "2 - 5 Years",
      shelfLifeOpened: "3 - 4 Days (Refrigerated)",
      storageType: "Cool Pantry (Below 85°F)",
      tips: "Discard cans with deep dents, bulges, rust, or leaks. Once opened, transfer unused contents out of the tin can into an airtight glass jar.",
      badge: "Emergency Essential",
    },
    {
      name: "Canned Tomatoes & Citrus",
      category: "canned",
      shelfLifePantry: "12 - 18 Months",
      shelfLifeOpened: "5 - 7 Days (Refrigerated)",
      storageType: "Cool, Dry Place",
      tips: "High-acid canned goods break down can linings faster than low-acid foods like beans or corn.",
      badge: "High Acid",
    },
    {
      name: "Soy Sauce & Tamari",
      category: "condiments",
      shelfLifePantry: "2 - 3 Years",
      shelfLifeOpened: "1 Month (Pantry) / 1+ Year (Fridge)",
      storageType: "Pantry (Unopened) / Fridge (Opened)",
      tips: "High sodium content prevents bacterial growth, but refrigeration preserves quality, color, and delicate flavor aromas.",
      badge: "Flavor Builder",
    },
    {
      name: "Extra Virgin Olive Oil",
      category: "condiments",
      shelfLifePantry: "12 - 18 Months",
      shelfLifeOpened: "3 - 6 Months",
      storageType: "Dark Glass Bottle, Cool Dark Cabinet",
      tips: "Light, air, and heat are olive oil's three enemies. Never store next to the hot stove top or on sunny windowsills.",
      badge: "Light Sensitive",
    },
    {
      name: "All-Purpose Flour",
      category: "baking",
      shelfLifePantry: "6 - 12 Months",
      shelfLifeOpened: "6 - 8 Months",
      storageType: "Airtight Container in Cool Dark Place",
      tips: "Freeze new flour bags for 48 hours after buying to eliminate potential bug eggs. Whole wheat flour spoils twice as fast as white flour.",
      badge: "Baking Core",
    },
    {
      name: "Honey (Pure, Raw)",
      category: "baking",
      shelfLifePantry: "Indefinite / Does Not Expire",
      shelfLifeOpened: "Indefinite",
      storageType: "Room Temp in Sealed Container",
      tips: "Crystallization is natural, not spoilage! Restore liquid texture by placing the sealed jar in a bowl of warm water.",
      badge: "Never Expires",
    },
  ];