const data = [
  {
    id: "rec-001",
    foodName: "Avocado Toast with Poached Egg",
    madeByCreator: "Chef Elena Rostova",
    time: {
      prepMinutes: 10,
      cookMinutes: 5,
      totalMinutes: 15,
    },
    image:
      "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=1200",
    category: "breakfast",
    ingredients: [
      "2 slices sourdough bread",
      "1 ripe avocado",
      "2 large eggs",
      "1 tbsp white vinegar",
      "1/4 tsp red pepper flakes",
      "Salt and black pepper to taste",
    ],
    instructions: [
      "Toast sourdough slices until golden brown.",
      "Mash avocado in a bowl with salt, pepper, and red pepper flakes.",
      "Bring a pot of water to a simmer with vinegar. Create a vortex and drop in eggs to poach for 3 minutes.",
      "Spread mashed avocado over toast and top with poached eggs.",
    ],
  },
  {
    id: "rec-002",
    foodName: "Classic Garlic Butter Steak Bites",
    madeByCreator: "Marcus Vance",
    time: {
      prepMinutes: 15,
      cookMinutes: 10,
      totalMinutes: 25,
    },
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=1200",
    category: "main",
    ingredients: [
      "1.5 lbs sirloin steak, cut into cubes",
      "3 tbsp unsalted butter",
      "4 cloves garlic, minced",
      "1 tbsp olive oil",
      "1 tbsp fresh parsley, chopped",
      "Salt and cracked pepper",
    ],
    instructions: [
      "Season steak cubes generously with salt and pepper.",
      "Heat olive oil in a heavy skillet over high heat until smoking.",
      "Sear steak bites for 3–4 minutes until a deep crust forms.",
      "Reduce heat, add butter and garlic, and toss for 1–2 minutes to coat. Garnish with parsley.",
    ],
  },
  {
    id: "rec-003",
    foodName: "Rich Chocolate Lava Cake",
    madeByCreator: "Sarah Jenkins",
    time: {
      prepMinutes: 15,
      cookMinutes: 12,
      totalMinutes: 27,
    },
    image:
      "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=1200",
    category: "desserts",
    ingredients: [
      "4 oz bittersweet chocolate",
      "1/2 cup unsalted butter",
      "2 eggs + 2 egg yolks",
      "1/4 cup sugar",
      "2 tbsp all-purpose flour",
      "Pinch of salt",
    ],
    instructions: [
      "Melt chocolate and butter together until smooth.",
      "Whisk eggs, yolks, and sugar until pale and slightly thick.",
      "Fold chocolate mixture and flour into the eggs until combined.",
      "Divide into greased ramekins and bake at 425°F (218°C) for 12 minutes. Serve warm.",
    ],
  },
  {
    id: "rec-004",
    foodName: "Iced Matcha Green Tea Latte",
    madeByCreator: "Kenji Takahashi",
    time: {
      prepMinutes: 5,
      cookMinutes: 0,
      totalMinutes: 5,
    },
    image:
      "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=1200",
    category: "drinks",
    ingredients: [
      "1.5 tsp ceremonial grade matcha powder",
      "2 tbsp warm water",
      "1 cup oat milk",
      "1 tbsp honey or maple syrup",
      "1 cup ice cubes",
    ],
    instructions: [
      "Sift matcha powder into a bowl to remove clumps.",
      "Add warm water and whisk vigorously in a bamboo motion until frothy.",
      "Fill a glass with ice and poured oat milk and sweetener over it.",
      "Pour the frothed matcha over top and stir well.",
    ],
  },
  {
    id: "rec-005",
    foodName: "Fluffy Blueberry Pancakes",
    madeByCreator: "Chef Elena Rostova",
    time: {
      prepMinutes: 10,
      cookMinutes: 15,
      totalMinutes: 25,
    },
    image:
      "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=1200",
    category: "breakfast",
    ingredients: [
      "1.5 cups all-purpose flour",
      "3.5 tsp baking powder",
      "1 tbsp sugar",
      "1.25 cups milk",
      "1 egg",
      "3 tbsp melted butter",
      "1 cup fresh blueberries",
    ],
    instructions: [
      "Sift together flour, baking powder, salt, and sugar in a large bowl.",
      "Whisk in milk, egg, and melted butter until smooth.",
      "Gently fold in fresh blueberries.",
      "Heat a lightly oiled griddle over medium-high heat and pour batter in 1/4 cup portions. Flip when bubbles form on top.",
    ],
  },
  {
    id: "rec-006",
    foodName: "Creamy Tuscan Garlic Chicken",
    madeByCreator: "Marcus Vance",
    time: {
      prepMinutes: 10,
      cookMinutes: 20,
      totalMinutes: 30,
    },
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=1200",
    category: "main",
    ingredients: [
      "2 large chicken breasts, halved lengthwise",
      "1 tbsp olive oil",
      "1 cup heavy cream",
      "1/2 cup chicken broth",
      "1 tsp garlic powder",
      "1 cup spinach",
      "1/2 cup sun-dried tomatoes, drained",
      "1/2 cup grated Parmesan cheese",
    ],
    instructions: [
      "Season chicken with salt, pepper, and garlic powder.",
      "Sear chicken in olive oil over medium-high heat for 5 minutes per side until cooked through; remove and set aside.",
      "In the same pan, add heavy cream, chicken broth, garlic powder, and Parmesan cheese. Bring to a simmer.",
      "Add spinach and sun-dried tomatoes; simmer until spinach wilts.",
      "Return chicken to the pan and coat in cream sauce before serving.",
    ],
  },
  {
    id: "rec-007",
    foodName: "Classic Italian Tiramisu",
    madeByCreator: "Sarah Jenkins",
    time: {
      prepMinutes: 25,
      cookMinutes: 0,
      totalMinutes: 25,
    },
    image:
      "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=1200",
    category: "desserts",
    ingredients: [
      "6 egg yolks",
      "3/4 cup granulated sugar",
      "2/3 cup milk",
      "1.25 cups heavy cream",
      "8 oz mascarpone cheese",
      "1 cup espresso, cooled",
      "1 pack ladyfingers",
      "Unsweetened cocoa powder for dusting",
    ],
    instructions: [
      "Whisk egg yolks and sugar over a double boiler until pale and thickened.",
      "Whip heavy cream and fold into softened mascarpone cheese.",
      "Dip ladyfingers quickly into cooled espresso and layer in an 8x8 baking dish.",
      "Spread half the mascarpone mixture over ladyfingers. Repeat with a second layer.",
      "Dust generously with cocoa powder and chill for at least 4 hours.",
    ],
  },
  {
    id: "rec-008",
    foodName: "Fresh Strawberry Mint Mojito Mocktail",
    madeByCreator: "Kenji Takahashi",
    time: {
      prepMinutes: 5,
      cookMinutes: 0,
      totalMinutes: 5,
    },
    image:
      "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=1200",
    category: "drinks",
    ingredients: [
      "4 fresh strawberries, hulled",
      "8 fresh mint leaves",
      "1 tbsp lime juice",
      "1 tbsp simple syrup",
      "1 cup sparkling water or club soda",
      "Crushed ice",
    ],
    instructions: [
      "Muddle strawberries, mint leaves, and lime juice in a tall glass.",
      "Fill glass to the top with crushed ice.",
      "Pour in simple syrup and top with sparkling water.",
      "Stir gently and garnish with a fresh mint sprig and strawberry slice.",
    ],
  },
];

export default data;
