const data = [
  {
    id: "rec-001",
    foodName: "Avocado Toast with Poached Egg",
    madeByCreator: "Chef Elena Rostova",
    time: 15,
    isFavorite: true,
    difficulty: "Easy",
    image:
      "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=1200",
    category: "Breakfast",
    ingredients: [
      "2 slices sourdough bread",
      "1 ripe avocado",
      "2 large eggs",
      "1 tbsp white vinegar",
      "1/4 tsp red pepper flakes",
      "Salt and black pepper to taste",
    ],
    instructions: [
      "Toast sourdough slices until golden brown.",
      "Mash avocado in a bowl with salt, pepper, and red pepper flakes.",
      "Bring a pot of water to a simmer with vinegar. Create a vortex and drop in eggs to poach for 3 minutes.",
      "Spread mashed avocado over toast and top with poached eggs.",
    ],
  },
  {
    id: "rec-002",
    foodName: "Classic Garlic Butter Steak Bites",
    madeByCreator: "Marcus Vance",
    time: 25,
    isFavorite: false,
    difficulty: "Easy",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=1200",
    category: "Main",
    ingredients: [
      "1.5 lbs sirloin steak, cut into cubes",
      "3 tbsp unsalted butter",
      "4 cloves garlic, minced",
      "1 tbsp olive oil",
      "1 tbsp fresh parsley, chopped",
      "Salt and cracked pepper",
    ],
    instructions: [
      "Season steak cubes generously with salt and pepper.",
      "Heat olive oil in a heavy skillet over high heat until smoking.",
      "Sear steak bites for 3–4 minutes until a deep crust forms.",
      "Reduce heat, add butter and garlic, and toss for 1–2 minutes to coat. Garnish with parsley.",
    ],
  },
  {
    id: "rec-003",
    foodName: "Rich Chocolate Lava Cake",
    madeByCreator: "Sarah Jenkins",
    time: 27,
    isFavorite: false,
    difficulty: "Medium",
    image:
      "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=1200",
    category: "Desserts",
    ingredients: [
      "4 oz bittersweet chocolate",
      "1/2 cup unsalted butter",
      "2 eggs + 2 egg yolks",
      "1/4 cup sugar",
      "2 tbsp all-purpose flour",
      "Pinch of salt",
    ],
    instructions: [
      "Melt chocolate and butter together until smooth.",
      "Whisk eggs, yolks, and sugar until pale and slightly thick.",
      "Fold chocolate mixture and flour into the eggs until combined.",
      "Divide into greased ramekins and bake at 425°F (218°C) for 12 minutes. Serve warm.",
    ],
  },
  {
    id: "rec-004",
    foodName: "Iced Matcha Green Tea Latte",
    madeByCreator: "Kenji Takahashi",
    time: 5,
    isFavorite: false,
    difficulty: "Easy",
    image:
      "https://images.unsplash.com/photo-1740885696809-722b11d505d5?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGljZWQlMjBtYXRjaGElMjBncmVlbiUyMHRlYSUyMGxhdHRlfGVufDB8MHwwfHx8Mg%3D%3D",
    category: "Drinks",
    ingredients: [
      "1.5 tsp ceremonial grade matcha powder",
      "2 tbsp warm water",
      "1 cup oat milk",
      "1 tbsp honey or maple syrup",
      "1 cup ice cubes",
    ],
    instructions: [
      "Sift matcha powder into a bowl to remove clumps.",
      "Add warm water and whisk vigorously in a bamboo motion until frothy.",
      "Fill a glass with ice and poured oat milk and sweetener over it.",
      "Pour the frothed matcha over top and stir well.",
    ],
  },
  {
    id: "rec-005",
    foodName: "Fluffy Blueberry Pancakes",
    madeByCreator: "Chef Elena Rostova",
    time: 25,
    isFavorite: false,
    difficulty: "Easy",
    image:
      "https://images.unsplash.com/photo-1598214886806-c87b84b7078b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Qmx1ZWJlcnJ5JTIwUGFuY2FrZXN8ZW58MHwwfDB8fHwy",
    category: "Breakfast",
    ingredients: [
      "1.5 cups all-purpose flour",
      "3.5 tsp baking powder",
      "1 tbsp sugar",
      "1.25 cups milk",
      "1 egg",
      "3 tbsp melted butter",
      "1 cup fresh blueberries",
    ],
    instructions: [
      "Sift together flour, baking powder, salt, and sugar in a large bowl.",
      "Whisk in milk, egg, and melted butter until smooth.",
      "Gently fold in fresh blueberries.",
      "Heat a lightly oiled griddle over medium-high heat and pour batter in 1/4 cup portions. Flip when bubbles form on top.",
    ],
  },
  {
    id: "rec-006",
    foodName: "Creamy Tuscan Garlic Chicken",
    madeByCreator: "Marcus Vance",
    time: 30,
    isFavorite: false,
    difficulty: "Medium",
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=1200",
    category: "Main",
    ingredients: [
      "2 large chicken breasts, halved lengthwise",
      "1 tbsp olive oil",
      "1 cup heavy cream",
      "1/2 cup chicken broth",
      "1 tsp garlic powder",
      "1 cup spinach",
      "1/2 cup sun-dried tomatoes, drained",
      "1/2 cup grated Parmesan cheese",
    ],
    instructions: [
      "Season chicken with salt, pepper, and garlic powder.",
      "Sear chicken in olive oil over medium-high heat for 5 minutes per side until cooked through; remove and set aside.",
      "In the same pan, add heavy cream, chicken broth, garlic powder, and Parmesan cheese. Bring to a simmer.",
      "Add spinach and sun-dried tomatoes; simmer until spinach wilts.",
      "Return chicken to the pan and coat in cream sauce before serving.",
    ],
  },
  {
    id: "rec-007",
    foodName: "Classic Italian Tiramisu",
    madeByCreator: "Sarah Jenkins",
    time: 25,
    isFavorite: false,
    difficulty: "Medium",
    image:
      "https://images.unsplash.com/photo-1639744211487-b27e3551b07c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8VGlyYW1pc3V8ZW58MHx8MHx8fDA%3D",
    category: "Desserts",
    ingredients: [
      "6 egg yolks",
      "3/4 cup granulated sugar",
      "2/3 cup milk",
      "1.25 cups heavy cream",
      "8 oz mascarpone cheese",
      "1 cup espresso, cooled",
      "1 pack ladyfingers",
      "Unsweetened cocoa powder for dusting",
    ],
    instructions: [
      "Whisk egg yolks and sugar over a double boiler until pale and thickened.",
      "Whip heavy cream and fold into softened mascarpone cheese.",
      "Dip ladyfingers quickly into cooled espresso and layer in an 8x8 baking dish.",
      "Spread half the mascarpone mixture over ladyfingers. Repeat with a second layer.",
      "Dust generously with cocoa powder and chill for at least 4 hours.",
    ],
  },
  {
    id: "rec-008",
    foodName: "Fresh Strawberry Mint Mojito Mocktail",
    madeByCreator: "Kenji Takahashi",
    time: 5,
    isFavorite: false,
    difficulty: "Easy",
    image:
      "https://images.unsplash.com/photo-1654074517219-85e6f3f6f85d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8U3RyYXdiZXJyeSUyME1pbnQlMjBNb2ppdG8lMjBNb2NrdGFpbHxlbnwwfHwwfHx8MA%3D%3D",
    category: "Drinks",
    ingredients: [
      "4 fresh strawberries, hulled",
      "8 fresh mint leaves",
      "1 tbsp lime juice",
      "1 tbsp simple syrup",
      "1 cup sparkling water or club soda",
      "Crushed ice",
    ],
    instructions: [
      "Muddle strawberries, mint leaves, and lime juice in a tall glass.",
      "Fill glass to the top with crushed ice.",
      "Pour in simple syrup and top with sparkling water.",
      "Stir gently and garnish with a fresh mint sprig and strawberry slice.",
    ],
  },
  {
    id: "rec-009",
    foodName: "Crisp French Onion Soup",
    madeByCreator: "Chef Elena Rostova",
    time: 60,
    isFavorite: false,
    difficulty: "Medium",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=1200",
    category: "Main",
    ingredients: [
      "4 large yellow onions, thinly sliced",
      "3 tbsp unsalted butter",
      "4 cups beef broth",
      "1/2 cup dry white wine",
      "1 baguette, sliced and toasted",
      "1 cup Gruyère cheese, shredded",
    ],
    instructions: [
      "Caramelize onions in melted butter over low heat for 40 minutes.",
      "Deglaze pan with white wine and simmer for 2 minutes.",
      "Add beef broth, simmer for 15 minutes, and season to taste.",
      "Ladle into oven-safe bowls, top with toasted baguette and Gruyère, then broil until golden.",
    ],
  },
  {
    id: "rec-010",
    foodName: "Classic Eggs Benedict",
    madeByCreator: "Marcus Vance",
    time: 25,
    isFavorite: false,
    difficulty: "Hard",
    image:
      "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=1200",
    category: "Breakfast",
    ingredients: [
      "2 English muffins, split and toasted",
      "4 slices Canadian bacon",
      "4 large eggs",
      "3 egg yolks",
      "1/2 cup unsalted butter, melted",
      "1 tbsp lemon juice",
    ],
    instructions: [
      "Whisk egg yolks and lemon juice over a double boiler, then slowly drizzle in melted butter to emulsify into hollandaise.",
      "Sear Canadian bacon in a skillet until browned.",
      "Poach eggs in simmering water for 3 minutes.",
      "Assemble by placing bacon and egg on toasted muffin, then top with hollandaise sauce.",
    ],
  },
  {
    id: "rec-011",
    foodName: "Mango Coconut Smoothie Bowl",
    madeByCreator: "Kenji Takahashi",
    time: 10,
    isFavorite: false,
    difficulty: "Easy",
    image:
      "https://images.unsplash.com/photo-1645839449196-62bde406052e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8TWFuZ28lMjBDb2NvbnV0JTIwU21vb3RoaWUlMjBCb3dsfGVufDB8MHwwfHx8Mg%3D%3D",
    category: "Breakfast",
    ingredients: [
      "2 cups frozen mango chunks",
      "1/2 cup coconut milk",
      "1 tbsp chia seeds",
      "1/4 cup sliced almonds",
      "1/2 cup fresh berries",
    ],
    instructions: [
      "Blend frozen mango chunks and coconut milk until thick and smooth.",
      "Pour mixture into a serving bowl.",
      "Top with chia seeds, sliced almonds, and fresh berries before serving.",
    ],
  },
  {
    id: "rec-012",
    foodName: "Spicy Creamy Rigatoni Alla Vodka",
    madeByCreator: "Chef Elena Rostova",
    time: 25,
    isFavorite: false,
    difficulty: "Easy",
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=1200",
    category: "Main",
    ingredients: [
      "1 lb rigatoni pasta",
      "2 tbsp olive oil",
      "1 small onion, diced",
      "2 cloves garlic, minced",
      "1/2 cup tomato paste",
      "2 tbsp vodka",
      "1/2 cup heavy cream",
      "1/2 tsp red pepper flakes",
    ],
    instructions: [
      "Boil rigatoni in salted water until al dente.",
      "Sauté onion and garlic in olive oil, then stir in tomato paste and red pepper flakes.",
      "Pour in vodka to deglaze, then stir in heavy cream until smooth.",
      "Toss pasta into sauce with a splash of pasta water.",
    ],
  },
  {
    id: "rec-013",
    foodName: "Authentic Beef Tacos",
    madeByCreator: "Marcus Vance",
    time: 20,
    isFavorite: false,
    difficulty: "Easy",
    image:
      "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=1200",
    category: "Main",
    ingredients: [
      "1 lb ground beef",
      "1 packet taco seasoning",
      "8 small corn tortillas",
      "1/2 cup diced white onion",
      "1/2 cup chopped fresh cilantro",
      "1 lime, cut into wedges",
    ],
    instructions: [
      "Brown ground beef in a pan over medium heat and drain excess fat.",
      "Stir in taco seasoning with 1/4 cup water and simmer for 5 minutes.",
      "Warm tortillas on a hot skillet.",
      "Fill tortillas with beef, onion, cilantro, and squeeze fresh lime on top.",
    ],
  },
  {
    id: "rec-014",
    foodName: "Decadent Fudgy Brownies",
    madeByCreator: "Sarah Jenkins",
    time: 40,
    isFavorite: false,
    difficulty: "Medium",
    image:
      "https://images.unsplash.com/photo-1461009312844-e80697a81cc7?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8YnJvd25pZXN8ZW58MHwwfDB8fHwy",
    category: "Desserts",
    ingredients: [
      "1/2 cup unsalted butter, melted",
      "1 cup granulated sugar",
      "2 large eggs",
      "1 tsp vanilla extract",
      "1/3 cup cocoa powder",
      "1/2 cup all-purpose flour",
      "1/2 cup chocolate chips",
    ],
    instructions: [
      "Mix melted butter, sugar, eggs, and vanilla extract in a bowl until smooth.",
      "Whisk in cocoa powder, flour, and salt until combined.",
      "Fold in chocolate chips and pour batter into an 8x8 greased baking pan.",
      "Bake at 350°F (175°C) for 25–30 minutes.",
    ],
  },
  {
    id: "rec-015",
    foodName: "Iced Caramel Macchiato",
    madeByCreator: "Kenji Takahashi",
    time: 5,
    isFavorite: false,
    difficulty: "Easy",
    image:
      "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=1200",
    category: "Drinks",
    ingredients: [
      "2 shots espresso",
      "1 cup milk of choice",
      "1 tbsp vanilla syrup",
      "2 tbsp caramel drizzle",
      "1 cup ice cubes",
    ],
    instructions: [
      "Pour vanilla syrup and milk into a glass filled with ice.",
      "Brew 2 espresso shots and pour directly over milk.",
      "Drizzle top liberally with caramel sauce and enjoy.",
    ],
  },
  {
    id: "rec-016",
    foodName: "Mediterranean Greek Salad",
    madeByCreator: "Chef Elena Rostova",
    time: 15,
    isFavorite: false,
    difficulty: "Easy",
    image:
      "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=1200",
    category: "Main",
    ingredients: [
      "2 large cucumbers, chopped",
      "4 Roma tomatoes, chopped",
      "1/2 red onion, thinly sliced",
      "1/2 cup Kalamata olives",
      "7 oz feta cheese, cubed",
      "3 tbsp extra virgin olive oil",
      "1 tbsp red wine vinegar",
    ],
    instructions: [
      "Combine cucumbers, tomatoes, red onion, and Kalamata olives in a large bowl.",
      "Whisk together olive oil, red wine vinegar, oregano, and salt.",
      "Pour dressing over vegetables and gently toss.",
      "Top with cubed feta cheese before serving.",
    ],
  },
  {
    id: "rec-017",
    foodName: "Classic Lemon Tart",
    madeByCreator: "Sarah Jenkins",
    time: 50,
    isFavorite: false,
    difficulty: "Hard",
    image:
      "https://images.unsplash.com/photo-1543508834-51a9bcc28a88?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8TGVtb24lMjBUYXJ0fGVufDB8MHwwfHx8Mg%3D%3D",
    category: "Desserts",
    ingredients: [
      "1 pre-baked tart crust",
      "4 large eggs",
      "1 cup granulated sugar",
      "1/2 cup fresh lemon juice",
      "2 tbsp lemon zest",
      "1/2 cup unsalted butter, cubed",
    ],
    instructions: [
      "Whisk eggs, sugar, lemon juice, and lemon zest in a saucepan over medium heat.",
      "Cook continuously until thickened, then remove from heat and whisk in butter pieces.",
      "Strain lemon curd into pre-baked crust.",
      "Bake at 325°F (165°C) for 15 minutes, then chill completely before serving.",
    ],
  },
  {
    id: "rec-018",
    foodName: "Homemade Margherita Pizza",
    madeByCreator: "Marcus Vance",
    time: 30,
    isFavorite: false,
    difficulty: "Medium",
    image:
      "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=1200",
    category: "Main",
    ingredients: [
      "1 lb pizza dough",
      "1/2 cup San Marzano tomato sauce",
      "8 oz fresh mozzarella, sliced",
      "Fresh basil leaves",
      "1 tbsp extra virgin olive oil",
    ],
    instructions: [
      "Stretch dough onto a pizza stone or pan.",
      "Spread tomato sauce evenly over dough and lay mozzarella slices on top.",
      "Bake at 500°F (260°C) for 10–12 minutes until crust is golden and cheese bubbles.",
      "Garnish with fresh basil leaves and drizzle with olive oil.",
    ],
  },
  {
    id: "rec-019",
    foodName: "Berry Sparkler Sangria",
    madeByCreator: "Kenji Takahashi",
    time: 10,
    isFavorite: false,
    difficulty: "Easy",
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=1200",
    category: "Drinks",
    ingredients: [
      "1 bottle white wine or Prosecco",
      "1/2 cup brandy",
      "1 cup mixed berries (strawberries, blueberries)",
      "1/2 cup lemon-lime soda",
      "1 lemon, sliced",
    ],
    instructions: [
      "Combine wine, brandy, and fruit slices in a large pitcher.",
      "Refrigerate for at least 1 hour to allow flavors to infuse.",
      "Stir in lemon-lime soda right before serving over ice.",
    ],
  },
  {
    id: "rec-020",
    foodName: "Crispy French Toast Bites",
    madeByCreator: "Chef Elena Rostova",
    time: 20,
    isFavorite: false,
    difficulty: "Easy",
    image:
      "https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=1200",
    category: "Breakfast",
    ingredients: [
      "4 slices thick brioche, cubed",
      "2 eggs",
      "1/4 cup milk",
      "1 tsp cinnamon",
      "2 tbsp butter",
      "Maple syrup for dipping",
    ],
    instructions: [
      "Whisk eggs, milk, and cinnamon together in a bowl.",
      "Dip brioche cubes into egg mixture to coat.",
      "Melt butter in a pan over medium heat and cook cubes for 2–3 minutes per side until golden.",
      "Dust with powdered sugar and serve with maple syrup.",
    ],
  },
  {
    id: "rec-021",
    foodName: "Classic Beef Pho",
    madeByCreator: "Kenji Takahashi",
    time: 90,
    isFavorite: false,
    difficulty: "Hard",
    image:
      "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=1200",
    category: "Main",
    ingredients: [
      "6 cups beef bone broth",
      "1 onion, charred",
      "1 ginger piece, charred",
      "2 star anise pods",
      "8 oz rice noodles",
      "1/2 lb thinly sliced sirloin",
      "Fresh herbs (cilantro, basil, mint)",
    ],
    instructions: [
      "Simmer bone broth with charred onion, ginger, and star anise for 1 hour.",
      "Cook rice noodles according to package directions and place in bowls.",
      "Arrange raw sirloin slices on top of noodles.",
      "Ladle boiling broth over beef to cook instantly; serve with fresh herbs.",
    ],
  },
  {
    id: "rec-022",
    foodName: "Creamy Vanilla Bean Panna Cotta",
    madeByCreator: "Sarah Jenkins",
    time: 20,
    isFavorite: false,
    difficulty: "Medium",
    image:
      "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=1200",
    category: "Desserts",
    ingredients: [
      "1 cup heavy cream",
      "1/2 cup whole milk",
      "1/4 cup sugar",
      "1 vanilla bean, split and scraped",
      "1.5 tsp powdered gelatin",
      "2 tbsp water",
    ],
    instructions: [
      "Bloom gelatin in water for 5 minutes.",
      "Heat heavy cream, milk, sugar, and vanilla bean in a saucepan until warm.",
      "Whisk in bloomed gelatin until dissolved.",
      "Pour into ramekins and chill in refrigerator for at least 4 hours until set.",
    ],
  },
  {
    id: "rec-023",
    foodName: "Classic Golden Turmeric Latte",
    madeByCreator: "Kenji Takahashi",
    time: 8,
    isFavorite: false,
    difficulty: "Easy",
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=1200",
    category: "Drinks",
    ingredients: [
      "1 cup almond milk",
      "1 tsp ground turmeric",
      "1/2 tsp ground cinnamon",
      "1/4 tsp ground ginger",
      "1 tbsp honey",
      "Pinch of black pepper",
    ],
    instructions: [
      "Combine almond milk, turmeric, cinnamon, ginger, and black pepper in a small saucepan.",
      "Heat over medium heat until warm, whisking constantly.",
      "Stir in honey, pour into a mug, and sprinkle with extra cinnamon.",
    ],
  },
  {
    id: "rec-024",
    foodName: "Savory Shakshuka",
    madeByCreator: "Chef Elena Rostova",
    time: 30,
    isFavorite: false,
    difficulty: "Medium",
    image:
      "https://images.unsplash.com/photo-1590412200988-a436970781fa?w=1200",
    category: "Breakfast",
    ingredients: [
      "1 tbsp olive oil",
      "1/2 yellow onion, chopped",
      "1 red bell pepper, chopped",
      "2 cloves garlic, minced",
      "1 can (14 oz) crushed tomatoes",
      "1 tsp cumin",
      "1 tsp paprika",
      "4 large eggs",
    ],
    instructions: [
      "Sauté onion, bell pepper, and garlic in olive oil until soft.",
      "Stir in crushed tomatoes, cumin, and paprika; simmer for 10 minutes.",
      "Make 4 small wells in sauce and crack an egg into each.",
      "Cover skillet and cook for 5–8 minutes until egg whites are set.",
    ],
  },
  {
    id: "rec-025",
    foodName: "Crispy Honey Garlic Salmon",
    madeByCreator: "Marcus Vance",
    time: 20,
    isFavorite: false,
    difficulty: "Easy",
    image:
      "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=1200",
    category: "Main",
    ingredients: [
      "2 salmon fillets",
      "2 tbsp soy sauce",
      "3 tbsp honey",
      "2 cloves garlic, minced",
      "1 tbsp olive oil",
      "1 tbsp lemon juice",
    ],
    instructions: [
      "Whisk soy sauce, honey, garlic, and lemon juice in a small bowl.",
      "Heat olive oil in a pan over medium-high heat and sear salmon skin-side down for 4 minutes.",
      "Flip salmon, pour honey garlic sauce into pan, and cook 3 minutes until glaze thickens.",
    ],
  },
  {
    id: "rec-026",
    foodName: "Classic Lemonade Frozen Slush",
    madeByCreator: "Kenji Takahashi",
    time: 5,
    isFavorite: false,
    difficulty: "Easy",
    image:
      "https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=1200",
    category: "Drinks",
    ingredients: [
      "1/2 cup fresh lemon juice",
      "1/3 cup simple syrup",
      "2 cups ice cubes",
      "1/2 cup water",
      "Lemon slices for garnish",
    ],
    instructions: [
      "Add lemon juice, simple syrup, water, and ice cubes to a blender.",
      "Blend on high until smooth and slushy.",
      "Pour into glasses and garnish with fresh lemon slices.",
    ],
  },
  {
    id: "rec-027",
    foodName: "Raspberry Cream Pavlova",
    madeByCreator: "Sarah Jenkins",
    time: 90,
    isFavorite: false,
    difficulty: "Hard",
    image:
      "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=1200",
    category: "Desserts",
    ingredients: [
      "4 egg whites",
      "1 cup caster sugar",
      "1 tsp white vinegar",
      "1 tsp cornstarch",
      "1 cup heavy cream, whipped",
      "1 cup fresh raspberries",
    ],
    instructions: [
      "Whip egg whites to soft peaks, then gradually add sugar until glossy and stiff.",
      "Fold in vinegar and cornstarch.",
      "Shape meringue on a parchment paper sheet and bake at 250°F (120°C) for 75 minutes.",
      "Cool completely, top with whipped cream and fresh raspberries.",
    ],
  },
  {
    id: "rec-028",
    foodName: "Classic Caesar Salad",
    madeByCreator: "Chef Elena Rostova",
    time: 15,
    isFavorite: false,
    difficulty: "Easy",
    image: "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=1200",
    category: "Main",
    ingredients: [
      "1 head Romaine lettuce, chopped",
      "1/2 cup Caesar dressing",
      "1/2 cup croutons",
      "1/3 cup grated Parmesan cheese",
      "Cracked black pepper",
    ],
    instructions: [
      "Toss chopped Romaine lettuce in a large salad bowl with Caesar dressing.",
      "Add croutons and grated Parmesan cheese.",
      "Toss gently until well coated and finish with cracked black pepper.",
    ],
  },
];

export default data;
