const data = [
  {
    id: "rec-001",
    foodName: "Avocado Toast with Poached Egg",
    madeByCreator: "Chef Elena Rostova",
    time: 15,
    isFavorite: true,
    difficulty: "Easy",
    image:
      "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=1200",
    category: "Breakfast",
    ingredients: [
      { quantity: 2, unit: "slices", name: "sourdough bread" },
      { quantity: 1, unit: "", name: "ripe avocado" },
      { quantity: 2, unit: "large", name: "eggs" },
      { quantity: 1, unit: "tbsp", name: "white vinegar" },
      { quantity: 0.25, unit: "tsp", name: "red pepper flakes" },
      { quantity: 0, unit: "", name: "Salt and black pepper to taste" },
    ],
    instructions: [
      "Toast sourdough slices until golden brown.",
      "Mash avocado in a bowl with salt, pepper, and red pepper flakes.",
      "Bring a pot of water to a simmer with vinegar. Create a vortex and drop in eggs to poach for 3 minutes.",
      "Spread mashed avocado over toast and top with poached eggs.",
    ],
  },
  {
    id: "rec-002",
    foodName: "Classic Garlic Butter Steak Bites",
    madeByCreator: "Marcus Vance",
    time: 25,
    isFavorite: false,
    difficulty: "Easy",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=1200",
    category: "Main",
    ingredients: [
      { quantity: 1.5, unit: "lbs", name: "sirloin steak, cut into cubes" },
      { quantity: 3, unit: "tbsp", name: "unsalted butter" },
      { quantity: 4, unit: "cloves", name: "garlic, minced" },
      { quantity: 1, unit: "tbsp", name: "olive oil" },
      { quantity: 1, unit: "tbsp", name: "fresh parsley, chopped" },
      { quantity: 0, unit: "", name: "Salt and cracked pepper" },
    ],
    instructions: [
      "Season steak cubes generously with salt and pepper.",
      "Heat olive oil in a heavy skillet over high heat until smoking.",
      "Sear steak bites for 3–4 minutes until a deep crust forms.",
      "Reduce heat, add butter and garlic, and toss for 1–2 minutes to coat. Garnish with parsley.",
    ],
  },
  {
    id: "rec-003",
    foodName: "Rich Chocolate Lava Cake",
    madeByCreator: "Sarah Jenkins",
    time: 27,
    isFavorite: false,
    difficulty: "Medium",
    image:
      "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=1200",
    category: "Desserts",
    ingredients: [
      { quantity: 4, unit: "oz", name: "bittersweet chocolate" },
      { quantity: 0.5, unit: "cup", name: "unsalted butter" },
      { quantity: 2, unit: "", name: "eggs + 2 egg yolks" },
      { quantity: 0.25, unit: "cup", name: "sugar" },
      { quantity: 2, unit: "tbsp", name: "all-purpose flour" },
      { quantity: 1, unit: "Pinch", name: "of salt" },
    ],
    instructions: [
      "Melt chocolate and butter together until smooth.",
      "Whisk eggs, yolks, and sugar until pale and slightly thick.",
      "Fold chocolate mixture and flour into the eggs until combined.",
      "Divide into greased ramekins and bake at 425°F (218°C) for 12 minutes. Serve warm.",
    ],
  },
  {
    id: "rec-004",
    foodName: "Iced Matcha Green Tea Latte",
    madeByCreator: "Kenji Takahashi",
    time: 5,
    isFavorite: false,
    difficulty: "Easy",
    image:
      "https://images.unsplash.com/photo-1740885696809-722b11d505d5?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGljZWQlMjBtYXRjaGElMjBncmVlbiUyMHRlYSUyMGxhdHRlfGVufDB8MHwwfHx8Mg%3D%3D",
    category: "Drinks",
    ingredients: [
      { quantity: 1.5, unit: "tsp", name: "ceremonial grade matcha powder" },
      { quantity: 2, unit: "tbsp", name: "warm water" },
      { quantity: 1, unit: "cup", name: "oat milk" },
      { quantity: 1, unit: "tbsp", name: "honey or maple syrup" },
      { quantity: 1, unit: "cup", name: "ice cubes" },
    ],
    instructions: [
      "Sift matcha powder into a bowl to remove clumps.",
      "Add warm water and whisk vigorously in a bamboo motion until frothy.",
      "Fill a glass with ice and poured oat milk and sweetener over it.",
      "Pour the frothed matcha over top and stir well.",
    ],
  },
  {
    id: "rec-005",
    foodName: "Fluffy Blueberry Pancakes",
    madeByCreator: "Chef Elena Rostova",
    time: 25,
    isFavorite: false,
    difficulty: "Easy",
    image:
      "https://images.unsplash.com/photo-1598214886806-c87b84b7078b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Qmx1ZWJlcnJ5JTIwUGFuY2FrZXN8ZW58MHwwfDB8fHwy",
    category: "Breakfast",
    ingredients: [
      { quantity: 1.5, unit: "cups", name: "all-purpose flour" },
      { quantity: 3.5, unit: "tsp", name: "baking powder" },
      { quantity: 1, unit: "tbsp", name: "sugar" },
      { quantity: 1.25, unit: "cups", name: "milk" },
      { quantity: 1, unit: "", name: "egg" },
      { quantity: 3, unit: "tbsp", name: "melted butter" },
      { quantity: 1, unit: "cup", name: "fresh blueberries" },
    ],
    instructions: [
      "Sift together flour, baking powder, salt, and sugar in a large bowl.",
      "Whisk in milk, egg, and melted butter until smooth.",
      "Gently fold in fresh blueberries.",
      "Heat a lightly oiled griddle over medium-high heat and pour batter in 1/4 cup portions. Flip when bubbles form on top.",
    ],
  },
  {
    id: "rec-006",
    foodName: "Creamy Tuscan Garlic Chicken",
    madeByCreator: "Marcus Vance",
    time: 30,
    isFavorite: false,
    difficulty: "Medium",
    image:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=1200",
    category: "Main",
    ingredients: [
      {
        quantity: 2,
        unit: "large",
        name: "chicken breasts, halved lengthwise",
      },
      { quantity: 1, unit: "tbsp", name: "olive oil" },
      { quantity: 1, unit: "cup", name: "heavy cream" },
      { quantity: 0.5, unit: "cup", name: "chicken broth" },
      { quantity: 1, unit: "tsp", name: "garlic powder" },
      { quantity: 1, unit: "cup", name: "spinach" },
      { quantity: 0.5, unit: "cup", name: "sun-dried tomatoes, drained" },
      { quantity: 0.5, unit: "cup", name: "grated Parmesan cheese" },
    ],
    instructions: [
      "Season chicken with salt, pepper, and garlic powder.",
      "Sear chicken in olive oil over medium-high heat for 5 minutes per side until cooked through; remove and set aside.",
      "In the same pan, add heavy cream, chicken broth, garlic powder, and Parmesan cheese. Bring to a simmer.",
      "Add spinach and sun-dried tomatoes; simmer until spinach wilts.",
      "Return chicken to the pan and coat in cream sauce before serving.",
    ],
  },
  {
    id: "rec-007",
    foodName: "Classic Italian Tiramisu",
    madeByCreator: "Sarah Jenkins",
    time: 25,
    isFavorite: false,
    difficulty: "Medium",
    image:
      "https://images.unsplash.com/photo-1639744211487-b27e3551b07c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8VGlyYW1pc3V8ZW58MHx8MHx8fDA%3D",
    category: "Desserts",
    ingredients: [
      { quantity: 6, unit: "", name: "egg yolks" },
      { quantity: 0.75, unit: "cup", name: "granulated sugar" },
      { quantity: 0.67, unit: "cup", name: "milk" },
      { quantity: 1.25, unit: "cups", name: "heavy cream" },
      { quantity: 8, unit: "oz", name: "mascarpone cheese" },
      { quantity: 1, unit: "cup", name: "espresso, cooled" },
      { quantity: 1, unit: "pack", name: "ladyfingers" },
      {
        quantity: 0,
        unit: "",
        name: "Unsweetened cocoa powder for dusting",
      },
    ],
    instructions: [
      "Whisk egg yolks and sugar over a double boiler until pale and thickened.",
      "Whip heavy cream and fold into softened mascarpone cheese.",
      "Dip ladyfingers quickly into cooled espresso and layer in an 8x8 baking dish.",
      "Spread half the mascarpone mixture over ladyfingers. Repeat with a second layer.",
      "Dust generously with cocoa powder and chill for at least 4 hours.",
    ],
  },
  {
    id: "rec-008",
    foodName: "Fresh Strawberry Mint Mojito Mocktail",
    madeByCreator: "Kenji Takahashi",
    time: 5,
    isFavorite: false,
    difficulty: "Easy",
    image:
      "https://images.unsplash.com/photo-1654074517219-85e6f3f6f85d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8U3RyYXdiZXJyeSUyME1pbnQlMjBNb2ppdG8lMjBNb2NrdGFpbHxlbnwwfHwwfHx8MA%3D%3D",
    category: "Drinks",
    ingredients: [
      { quantity: 4, unit: "fresh", name: "strawberries, hulled" },
      { quantity: 8, unit: "fresh", name: "mint leaves" },
      { quantity: 1, unit: "tbsp", name: "lime juice" },
      { quantity: 1, unit: "tbsp", name: "simple syrup" },
      { quantity: 1, unit: "cup", name: "sparkling water or club soda" },
      { quantity: 0, unit: "", name: "Crushed ice" },
    ],
    instructions: [
      "Muddle strawberries, mint leaves, and lime juice in a tall glass.",
      "Fill glass to the top with crushed ice.",
      "Pour in simple syrup and top with sparkling water.",
      "Stir gently and garnish with a fresh mint sprig and strawberry slice.",
    ],
  },
  {
    id: "rec-009",
    foodName: "Crisp French Onion Soup",
    madeByCreator: "Chef Elena Rostova",
    time: 60,
    isFavorite: false,
    difficulty: "Medium",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=1200",
    category: "Main",
    ingredients: [
      { quantity: 4, unit: "large", name: "yellow onions, thinly sliced" },
      { quantity: 3, unit: "tbsp", name: "unsalted butter" },
      { quantity: 4, unit: "cups", name: "beef broth" },
      { quantity: 0.5, unit: "cup", name: "dry white wine" },
      { quantity: 1, unit: "", name: "baguette, sliced and toasted" },
      { quantity: 1, unit: "cup", name: "Gruyère cheese, shredded" },
    ],
    instructions: [
      "Caramelize onions in melted butter over low heat for 40 minutes.",
      "Deglaze pan with white wine and simmer for 2 minutes.",
      "Add beef broth, simmer for 15 minutes, and season to taste.",
      "Ladle into oven-safe bowls, top with toasted baguette and Gruyère, then broil until golden.",
    ],
  },
  {
    id: "rec-010",
    foodName: "Classic Eggs Benedict",
    madeByCreator: "Marcus Vance",
    time: 25,
    isFavorite: false,
    difficulty: "Hard",
    image:
      "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=1200",
    category: "Breakfast",
    ingredients: [
      { quantity: 2, unit: "English", name: "muffins, split and toasted" },
      { quantity: 4, unit: "slices", name: "Canadian bacon" },
      { quantity: 4, unit: "large", name: "eggs" },
      { quantity: 3, unit: "", name: "egg yolks" },
      { quantity: 0.5, unit: "cup", name: "unsalted butter, melted" },
      { quantity: 1, unit: "tbsp", name: "lemon juice" },
    ],
    instructions: [
      "Whisk egg yolks and lemon juice over a double boiler, then slowly drizzle in melted butter to emulsify into hollandaise.",
      "Sear Canadian bacon in a skillet until browned.",
      "Poach eggs in simmering water for 3 minutes.",
      "Assemble by placing bacon and egg on toasted muffin, then top with hollandaise sauce.",
    ],
  },
  {
    id: "rec-011",
    foodName: "Mango Coconut Smoothie Bowl",
    madeByCreator: "Kenji Takahashi",
    time: 10,
    isFavorite: false,
    difficulty: "Easy",
    image:
      "https://images.unsplash.com/photo-1645839449196-62bde406052e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8TWFuZ28lMjBDb2NvbnV0JTIwU21vb3RoaWUlMjBCb3dsfGVufDB8MHwwfHx8Mg%3D%3D",
    category: "Breakfast",
    ingredients: [
      { quantity: 2, unit: "cups", name: "frozen mango chunks" },
      { quantity: 0.5, unit: "cup", name: "coconut milk" },
      { quantity: 1, unit: "tbsp", name: "chia seeds" },
      { quantity: 0.25, unit: "cup", name: "sliced almonds" },
      { quantity: 0.5, unit: "cup", name: "fresh berries" },
    ],
    instructions: [
      "Blend frozen mango chunks and coconut milk until thick and smooth.",
      "Pour mixture into a serving bowl.",
      "Top with chia seeds, sliced almonds, and fresh berries before serving.",
    ],
  },
  {
    id: "rec-012",
    foodName: "Spicy Creamy Rigatoni Alla Vodka",
    madeByCreator: "Chef Elena Rostova",
    time: 25,
    isFavorite: false,
    difficulty: "Easy",
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=1200",
    category: "Main",
    ingredients: [
      { quantity: 1, unit: "lb", name: "rigatoni pasta" },
      { quantity: 2, unit: "tbsp", name: "olive oil" },
      { quantity: 1, unit: "small", name: "onion, diced" },
      { quantity: 2, unit: "cloves", name: "garlic, minced" },
      { quantity: 0.5, unit: "cup", name: "tomato paste" },
      { quantity: 2, unit: "tbsp", name: "vodka" },
      { quantity: 0.5, unit: "cup", name: "heavy cream" },
      { quantity: 0.5, unit: "tsp", name: "red pepper flakes" },
    ],
    instructions: [
      "Boil rigatoni in salted water until al dente.",
      "Sauté onion and garlic in olive oil, then stir in tomato paste and red pepper flakes.",
      "Pour in vodka to deglaze, then stir in heavy cream until smooth.",
      "Toss pasta into sauce with a splash of pasta water.",
    ],
  },
  {
    id: "rec-013",
    foodName: "Authentic Beef Tacos",
    madeByCreator: "Marcus Vance",
    time: 20,
    isFavorite: false,
    difficulty: "Easy",
    image:
      "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=1200",
    category: "Main",
    ingredients: [
      { quantity: 1, unit: "lb", name: "ground beef" },
      { quantity: 1, unit: "packet", name: "taco seasoning" },
      { quantity: 8, unit: "small", name: "corn tortillas" },
      { quantity: 0.5, unit: "cup", name: "diced white onion" },
      { quantity: 0.5, unit: "cup", name: "chopped fresh cilantro" },
      { quantity: 1, unit: "", name: "lime, cut into wedges" },
    ],
    instructions: [
      "Brown ground beef in a pan over medium heat and drain excess fat.",
      "Stir in taco seasoning with 1/4 cup water and simmer for 5 minutes.",
      "Warm tortillas on a hot skillet.",
      "Fill tortillas with beef, onion, cilantro, and squeeze fresh lime on top.",
    ],
  },
  {
    id: "rec-014",
    foodName: "Decadent Fudgy Brownies",
    madeByCreator: "Sarah Jenkins",
    time: 40,
    isFavorite: false,
    difficulty: "Medium",
    image:
      "https://images.unsplash.com/photo-1461009312844-e80697a81cc7?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8YnJvd25pZXN8ZW58MHwwfDB8fHwy",
    category: "Desserts",
    ingredients: [
      { quantity: 0.5, unit: "cup", name: "unsalted butter, melted" },
      { quantity: 1, unit: "cup", name: "granulated sugar" },
      { quantity: 2, unit: "large", name: "eggs" },
      { quantity: 1, unit: "tsp", name: "vanilla extract" },
      { quantity: 0.33, unit: "cup", name: "cocoa powder" },
      { quantity: 0.5, unit: "cup", name: "all-purpose flour" },
      { quantity: 0.5, unit: "cup", name: "chocolate chips" },
    ],
    instructions: [
      "Mix melted butter, sugar, eggs, and vanilla extract in a bowl until smooth.",
      "Whisk in cocoa powder, flour, and salt until combined.",
      "Fold in chocolate chips and pour batter into an 8x8 greased baking pan.",
      "Bake at 350°F (175°C) for 25–30 minutes.",
    ],
  },
  {
    id: "rec-015",
    foodName: "Iced Caramel Macchiato",
    madeByCreator: "Kenji Takahashi",
    time: 5,
    isFavorite: false,
    difficulty: "Easy",
    image:
      "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=1200",
    category: "Drinks",
    ingredients: [
      { quantity: 2, unit: "shots", name: "espresso" },
      { quantity: 1, unit: "cup", name: "milk of choice" },
      { quantity: 1, unit: "tbsp", name: "vanilla syrup" },
      { quantity: 2, unit: "tbsp", name: "caramel drizzle" },
      { quantity: 1, unit: "cup", name: "ice cubes" },
    ],
    instructions: [
      "Pour vanilla syrup and milk into a glass filled with ice.",
      "Brew 2 espresso shots and pour directly over milk.",
      "Drizzle top liberally with caramel sauce and enjoy.",
    ],
  },
  {
    id: "rec-016",
    foodName: "Mediterranean Greek Salad",
    madeByCreator: "Chef Elena Rostova",
    time: 15,
    isFavorite: false,
    difficulty: "Easy",
    image:
      "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=1200",
    category: "Main",
    ingredients: [
      { quantity: 2, unit: "large", name: "cucumbers, chopped" },
      { quantity: 4, unit: "Roma", name: "tomatoes, chopped" },
      { quantity: 0.5, unit: "", name: "red onion, thinly sliced" },
      { quantity: 0.5, unit: "cup", name: "Kalamata olives" },
      { quantity: 7, unit: "oz", name: "feta cheese, cubed" },
      { quantity: 3, unit: "tbsp", name: "extra virgin olive oil" },
      { quantity: 1, unit: "tbsp", name: "red wine vinegar" },
    ],
    instructions: [
      "Combine cucumbers, tomatoes, red onion, and Kalamata olives in a large bowl.",
      "Whisk together olive oil, red wine vinegar, oregano, and salt.",
      "Pour dressing over vegetables and gently toss.",
      "Top with cubed feta cheese before serving.",
    ],
  },
  {
    id: "rec-017",
    foodName: "Classic Lemon Tart",
    madeByCreator: "Sarah Jenkins",
    time: 50,
    isFavorite: false,
    difficulty: "Hard",
    image:
      "https://images.unsplash.com/photo-1543508834-51a9bcc28a88?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8TGVtb24lMjBUYXJ0fGVufDB8MHwwfHx8Mg%3D%3D",
    category: "Desserts",
    ingredients: [
      { quantity: 1, unit: "", name: "pre-baked tart crust" },
      { quantity: 4, unit: "large", name: "eggs" },
      { quantity: 1, unit: "cup", name: "granulated sugar" },
      { quantity: 0.5, unit: "cup", name: "fresh lemon juice" },
      { quantity: 2, unit: "tbsp", name: "lemon zest" },
      { quantity: 0.5, unit: "cup", name: "unsalted butter, cubed" },
    ],
    instructions: [
      "Whisk eggs, sugar, lemon juice, and lemon zest in a saucepan over medium heat.",
      "Cook continuously until thickened, then remove from heat and whisk in butter pieces.",
      "Strain lemon curd into pre-baked crust.",
      "Bake at 325°F (165°C) for 15 minutes, then chill completely before serving.",
    ],
  },
  {
    id: "rec-018",
    foodName: "Homemade Margherita Pizza",
    madeByCreator: "Marcus Vance",
    time: 30,
    isFavorite: false,
    difficulty: "Medium",
    image:
      "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=1200",
    category: "Main",
    ingredients: [
      { quantity: 1, unit: "lb", name: "pizza dough" },
      { quantity: 0.5, unit: "cup", name: "San Marzano tomato sauce" },
      { quantity: 8, unit: "oz", name: "fresh mozzarella, sliced" },
      { quantity: 0, unit: "", name: "Fresh basil leaves" },
      { quantity: 1, unit: "tbsp", name: "extra virgin olive oil" },
    ],
    instructions: [
      "Stretch dough onto a pizza stone or pan.",
      "Spread tomato sauce evenly over dough and lay mozzarella slices on top.",
      "Bake at 500°F (260°C) for 10–12 minutes until crust is golden and cheese bubbles.",
      "Garnish with fresh basil leaves and drizzle with olive oil.",
    ],
  },
  {
    id: "rec-019",
    foodName: "Berry Sparkler Sangria",
    madeByCreator: "Kenji Takahashi",
    time: 10,
    isFavorite: false,
    difficulty: "Easy",
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=1200",
    category: "Drinks",
    ingredients: [
      { quantity: 1, unit: "bottle", name: "white wine or Prosecco" },
      { quantity: 0.5, unit: "cup", name: "brandy" },
      {
        quantity: 1,
        unit: "cup",
        name: "mixed berries (strawberries, blueberries)",
      },
      { quantity: 0.5, unit: "cup", name: "lemon-lime soda" },
      { quantity: 1, unit: "", name: "lemon, sliced" },
    ],
    instructions: [
      "Combine wine, brandy, and fruit slices in a large pitcher.",
      "Refrigerate for at least 1 hour to allow flavors to infuse.",
      "Stir in lemon-lime soda right before serving over ice.",
    ],
  },
  {
    id: "rec-020",
    foodName: "Crispy French Toast Bites",
    madeByCreator: "Chef Elena Rostova",
    time: 20,
    isFavorite: false,
    difficulty: "Easy",
    image:
      "https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=1200",
    category: "Breakfast",
    ingredients: [
      { quantity: 4, unit: "slices", name: "thick brioche, cubed" },
      { quantity: 2, unit: "", name: "eggs" },
      { quantity: 0.25, unit: "cup", name: "milk" },
      { quantity: 1, unit: "tsp", name: "cinnamon" },
      { quantity: 2, unit: "tbsp", name: "butter" },
      { quantity: 0, unit: "", name: "Maple syrup for dipping" },
    ],
    instructions: [
      "Whisk eggs, milk, and cinnamon together in a bowl.",
      "Dip brioche cubes into egg mixture to coat.",
      "Melt butter in a pan over medium heat and cook cubes for 2–3 minutes per side until golden.",
      "Dust with powdered sugar and serve with maple syrup.",
    ],
  },
  {
    id: "rec-021",
    foodName: "Classic Beef Pho",
    madeByCreator: "Kenji Takahashi",
    time: 90,
    isFavorite: false,
    difficulty: "Hard",
    image:
      "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=1200",
    category: "Main",
    ingredients: [
      { quantity: 6, unit: "cups", name: "beef bone broth" },
      { quantity: 1, unit: "", name: "onion, charred" },
      { quantity: 1, unit: "piece", name: "ginger, charred" },
      { quantity: 2, unit: "pods", name: "star anise" },
      { quantity: 8, unit: "oz", name: "rice noodles" },
      { quantity: 0.5, unit: "lb", name: "thinly sliced sirloin" },
      { quantity: 0, unit: "", name: "Fresh herbs (cilantro, basil, mint)" },
    ],
    instructions: [
      "Simmer bone broth with charred onion, ginger, and star anise for 1 hour.",
      "Cook rice noodles according to package directions and place in bowls.",
      "Arrange raw sirloin slices on top of noodles.",
      "Ladle boiling broth over beef to cook instantly; serve with fresh herbs.",
    ],
  },
  {
    id: "rec-022",
    foodName: "Creamy Vanilla Bean Panna Cotta",
    madeByCreator: "Sarah Jenkins",
    time: 20,
    isFavorite: false,
    difficulty: "Medium",
    image:
      "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=1200",
    category: "Desserts",
    ingredients: [
      { quantity: 1, unit: "cup", name: "heavy cream" },
      { quantity: 0.5, unit: "cup", name: "whole milk" },
      { quantity: 0.25, unit: "cup", name: "sugar" },
      { quantity: 1, unit: "bean", name: "vanilla, split and scraped" },
      { quantity: 1.5, unit: "tsp", name: "powdered gelatin" },
      { quantity: 2, unit: "tbsp", name: "water" },
    ],
    instructions: [
      "Bloom gelatin in water for 5 minutes.",
      "Heat heavy cream, milk, sugar, and vanilla bean in a saucepan until warm.",
      "Whisk in bloomed gelatin until dissolved.",
      "Pour into ramekins and chill in refrigerator for at least 4 hours until set.",
    ],
  },
  {
    id: "rec-023",
    foodName: "Classic Golden Turmeric Latte",
    madeByCreator: "Kenji Takahashi",
    time: 8,
    isFavorite: false,
    difficulty: "Easy",
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=1200",
    category: "Drinks",
    ingredients: [
      { quantity: 1, unit: "cup", name: "almond milk" },
      { quantity: 1, unit: "tsp", name: "ground turmeric" },
      { quantity: 0.5, unit: "tsp", name: "ground cinnamon" },
      { quantity: 0.25, unit: "tsp", name: "ground ginger" },
      { quantity: 1, unit: "tbsp", name: "honey" },
      { quantity: 1, unit: "Pinch", name: "of black pepper" },
    ],
    instructions: [
      "Combine almond milk, turmeric, cinnamon, ginger, and black pepper in a small saucepan.",
      "Heat over medium heat until warm, whisking constantly.",
      "Stir in honey, pour into a mug, and sprinkle with extra cinnamon.",
    ],
  },
  {
    id: "rec-024",
    foodName: "Savory Shakshuka",
    madeByCreator: "Chef Elena Rostova",
    time: 30,
    isFavorite: false,
    difficulty: "Medium",
    image:
      "https://images.unsplash.com/photo-1590412200988-a436970781fa?w=1200",
    category: "Breakfast",
    ingredients: [
      { quantity: 1, unit: "tbsp", name: "olive oil" },
      { quantity: 0.5, unit: "", name: "yellow onion, chopped" },
      { quantity: 1, unit: "", name: "red bell pepper, chopped" },
      { quantity: 2, unit: "cloves", name: "garlic, minced" },
      { quantity: 1, unit: "can", name: "(14 oz) crushed tomatoes" },
      { quantity: 1, unit: "tsp", name: "cumin" },
      { quantity: 1, unit: "tsp", name: "paprika" },
      { quantity: 4, unit: "large", name: "eggs" },
    ],
    instructions: [
      "Sauté onion, bell pepper, and garlic in olive oil until soft.",
      "Stir in crushed tomatoes, cumin, and paprika; simmer for 10 minutes.",
      "Make 4 small wells in sauce and crack an egg into each.",
      "Cover skillet and cook for 5–8 minutes until egg whites are set.",
    ],
  },
  {
    id: "rec-025",
    foodName: "Crispy Honey Garlic Salmon",
    madeByCreator: "Marcus Vance",
    time: 20,
    isFavorite: false,
    difficulty: "Easy",
    image:
      "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=1200",
    category: "Main",
    ingredients: [
      { quantity: 2, unit: "", name: "salmon fillets" },
      { quantity: 2, unit: "tbsp", name: "soy sauce" },
      { quantity: 3, unit: "tbsp", name: "honey" },
      { quantity: 2, unit: "cloves", name: "garlic, minced" },
      { quantity: 1, unit: "tbsp", name: "olive oil" },
      { quantity: 1, unit: "tbsp", name: "lemon juice" },
    ],
    instructions: [
      "Whisk soy sauce, honey, garlic, and lemon juice in a small bowl.",
      "Heat olive oil in a pan over medium-high heat and sear salmon skin-side down for 4 minutes.",
      "Flip salmon, pour honey garlic sauce into pan, and cook 3 minutes until glaze thickens.",
    ],
  },
  {
    id: "rec-026",
    foodName: "Classic Lemonade Frozen Slush",
    madeByCreator: "Kenji Takahashi",
    time: 5,
    isFavorite: false,
    difficulty: "Easy",
    image:
      "https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=1200",
    category: "Drinks",
    ingredients: [
      { quantity: 0.5, unit: "cup", name: "fresh lemon juice" },
      { quantity: 0.33, unit: "cup", name: "simple syrup" },
      { quantity: 2, unit: "cups", name: "ice cubes" },
      { quantity: 0.5, unit: "cup", name: "water" },
      { quantity: 0, unit: "", name: "Lemon slices for garnish" },
    ],
    instructions: [
      "Add lemon juice, simple syrup, water, and ice cubes to a blender.",
      "Blend on high until smooth and slushy.",
      "Pour into glasses and garnish with fresh lemon slices.",
    ],
  },
  {
    id: "rec-027",
    foodName: "Raspberry Cream Pavlova",
    madeByCreator: "Sarah Jenkins",
    time: 90,
    isFavorite: false,
    difficulty: "Hard",
    image:
      "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=1200",
    category: "Desserts",
    ingredients: [
      { quantity: 4, unit: "", name: "egg whites" },
      { quantity: 1, unit: "cup", name: "caster sugar" },
      { quantity: 1, unit: "tsp", name: "white vinegar" },
      { quantity: 1, unit: "tsp", name: "cornstarch" },
      { quantity: 1, unit: "cup", name: "heavy cream, whipped" },
      { quantity: 1, unit: "cup", name: "fresh raspberries" },
    ],
    instructions: [
      "Whip egg whites to soft peaks, then gradually add sugar until glossy and stiff.",
      "Fold in vinegar and cornstarch.",
      "Shape meringue on a parchment paper sheet and bake at 250°F (120°C) for 75 minutes.",
      "Cool completely, top with whipped cream and fresh raspberries.",
    ],
  },
  {
    id: "rec-028",
    foodName: "Classic Caesar Salad",
    madeByCreator: "Chef Elena Rostova",
    time: 15,
    isFavorite: false,
    difficulty: "Easy",
    image: "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=1200",
    category: "Main",
    ingredients: [
      { quantity: 1, unit: "head", name: "Romaine lettuce, chopped" },
      { quantity: 0.5, unit: "cup", name: "Caesar dressing" },
      { quantity: 0.5, unit: "cup", name: "croutons" },
      { quantity: 0.33, unit: "cup", name: "grated Parmesan cheese" },
      { quantity: 0, unit: "", name: "Cracked black pepper" },
    ],
    instructions: [
      "Toss chopped Romaine lettuce in a large salad bowl with Caesar dressing.",
      "Add croutons and grated Parmesan cheese.",
      "Toss gently until well coated and finish with cracked black pepper.",
    ],
  },
  {
    id: "rec-029",
    foodName: "Creamy Wild Mushroom Risotto",
    madeByCreator: "Chef Elena Rostova",
    time: 45,
    isFavorite: false,
    difficulty: "Medium",
    image:
      "https://images.unsplash.com/photo-1633964913295-ceb43826e7c9?w=1200",
    category: "Main",
    ingredients: [
      { quantity: 1.5, unit: "cups", name: "Arborio rice" },
      { quantity: 8, unit: "oz", name: "mixed wild mushrooms, sliced" },
      { quantity: 4, unit: "cups", name: "warm vegetable or chicken broth" },
      { quantity: 0.5, unit: "cup", name: "dry white wine" },
      { quantity: 1, unit: "small", name: "yellow onion, finely diced" },
      { quantity: 2, unit: "cloves", name: "garlic, minced" },
      { quantity: 0.5, unit: "cup", name: "grated Parmesan cheese" },
      { quantity: 2, unit: "tbsp", name: "unsalted butter" },
      { quantity: 2, unit: "tbsp", name: "olive oil" },
    ],
    instructions: [
      "Sauté mushrooms in 1 tbsp olive oil until browned; set aside.",
      "In a deep pan, heat remaining oil and butter to cook onion and garlic until soft.",
      "Add Arborio rice and toast for 2 minutes until translucent at edges.",
      "Pour in white wine and stir until absorbed.",
      "Add warm broth 1 ladle at a time, stirring constantly until absorbed before adding more.",
      "Fold in cooked mushrooms and Parmesan cheese just before serving.",
    ],
  },
  {
    id: "rec-030",
    foodName: "Sparkling Hibiscus Berry Iced Tea",
    madeByCreator: "Kenji Takahashi",
    time: 10,
    isFavorite: false,
    difficulty: "Easy",
    image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=1200",
    category: "Drinks",
    ingredients: [
      { quantity: 2, unit: "hibiscus", name: "tea bags" },
      { quantity: 1, unit: "cup", name: "boiling water" },
      { quantity: 0.5, unit: "cup", name: "sparkling water" },
      { quantity: 1, unit: "tbsp", name: "honey or agave syrup" },
      { quantity: 0.25, unit: "cup", name: "fresh blackberries" },
      { quantity: 1, unit: "tbsp", name: "fresh lime juice" },
      { quantity: 0, unit: "", name: "Ice cubes" },
    ],
    instructions: [
      "Steep hibiscus tea bags in boiling water for 5 minutes, then cool.",
      "Muddle blackberries and lime juice at the bottom of a glass.",
      "Fill glass with ice cubes.",
      "Pour in cooled hibiscus tea and sweetener, then top off with sparkling water.",
    ],
  },
  {
    id: "rec-031",
    foodName: "Classic French Crêpes",
    madeByCreator: "Sarah Jenkins",
    time: 20,
    isFavorite: false,
    difficulty: "Medium",
    image:
      "https://images.unsplash.com/photo-1519676867240-f03562e64548?w=1200",
    category: "Breakfast",
    ingredients: [
      { quantity: 1, unit: "cup", name: "all-purpose flour" },
      { quantity: 2, unit: "large", name: "eggs" },
      { quantity: 0.5, unit: "cup", name: "milk" },
      { quantity: 0.5, unit: "cup", name: "water" },
      { quantity: 0.25, unit: "tsp", name: "salt" },
      { quantity: 2, unit: "tbsp", name: "melted butter" },
      { quantity: 0, unit: "", name: "Nutella or fresh fruit for serving" },
    ],
    instructions: [
      "Whisk flour, eggs, milk, water, salt, and melted butter together until completely smooth.",
      "Heat a lightly oiled skillet over medium-high heat.",
      "Pour 1/4 cup batter into pan, tilting in a circular motion to coat surface thinly.",
      "Cook for 2 minutes until bottom is light golden, then flip and cook 1 minute more.",
      "Serve warm filled with Nutella or fresh berries.",
    ],
  },
  {
    id: "rec-032",
    foodName: "Crispy Teriyaki Chicken Bowl",
    madeByCreator: "Marcus Vance",
    time: 25,
    isFavorite: false,
    difficulty: "Easy",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=1200",
    category: "Main",
    ingredients: [
      {
        quantity: 1.5,
        unit: "lbs",
        name: "chicken thighs, boneless and skinless",
      },
      { quantity: 0.33, unit: "cup", name: "soy sauce" },
      { quantity: 2, unit: "tbsp", name: "mirin" },
      { quantity: 2, unit: "tbsp", name: "brown sugar" },
      { quantity: 1, unit: "clove", name: "garlic, minced" },
      { quantity: 1, unit: "tsp", name: "cornstarch mixed with 1 tbsp water" },
      { quantity: 2, unit: "cups", name: "cooked jasmine rice" },
      { quantity: 0, unit: "", name: "Steamed broccoli florets" },
    ],
    instructions: [
      "Pan-sear chicken thighs in a skillet over high heat until browned and cooked through; chop into bites.",
      "In a small saucepan, combine soy sauce, mirin, brown sugar, and garlic; bring to a simmer.",
      "Stir in cornstarch slurry and cook until sauce thickens into a glossy glaze.",
      "Toss chicken in glaze and serve over jasmine rice with steamed broccoli.",
    ],
  },
  {
    id: "rec-033",
    foodName: "Soft Glazed Cinnamon Rolls",
    madeByCreator: "Sarah Jenkins",
    time: 120,
    isFavorite: false,
    difficulty: "Hard",
    image:
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=1200",
    category: "Breakfast",
    ingredients: [
      { quantity: 3, unit: "cups", name: "all-purpose flour" },
      { quantity: 1, unit: "packet", name: "active dry yeast" },
      { quantity: 0.75, unit: "cup", name: "warm milk" },
      { quantity: 0.25, unit: "cup", name: "granulated sugar" },
      { quantity: 0.33, unit: "cup", name: "softened butter" },
      { quantity: 1, unit: "tbsp", name: "ground cinnamon" },
      { quantity: 0.5, unit: "cup", name: "brown sugar" },
      { quantity: 4, unit: "oz", name: "cream cheese" },
      { quantity: 1, unit: "cup", name: "powdered sugar" },
    ],
    instructions: [
      "Activate yeast in warm milk with 1 tbsp sugar for 10 minutes.",
      "Knead flour, yeast mixture, butter, and remaining sugar into a smooth dough; let rise 1 hour.",
      "Roll dough flat, spread softened butter, brown sugar, and cinnamon across top.",
      "Roll tightly into a log, slice into 9 pinwheels, and bake at 350°F (175°C) for 25 minutes.",
      "Whisk cream cheese and powdered sugar into a glaze and spread over warm rolls.",
    ],
  },
  {
    id: "rec-034",
    foodName: "Classic Espresso Martini",
    madeByCreator: "Kenji Takahashi",
    time: 5,
    isFavorite: false,
    difficulty: "Easy",
    image: "https://images.unsplash.com/photo-1545438102-799c3991ffb2?w=1200",
    category: "Drinks",
    ingredients: [
      { quantity: 2, unit: "oz", name: "vodka" },
      { quantity: 1, unit: "oz", name: "coffee liqueur" },
      { quantity: 1, unit: "oz", name: "fresh hot espresso" },
      { quantity: 0.5, unit: "oz", name: "simple syrup" },
      { quantity: 0, unit: "", name: "Whole coffee beans for garnish" },
      { quantity: 0, unit: "", name: "Ice cubes" },
    ],
    instructions: [
      "Brew 1 shot of hot, fresh espresso.",
      "Fill a cocktail shaker to the top with ice cubes.",
      "Add vodka, coffee liqueur, simple syrup, and espresso.",
      "Shake vigorously for 20 seconds to produce a rich froth.",
      "Strain into a chilled martini glass and top with 3 coffee beans.",
    ],
  },
  {
    id: "rec-035",
    foodName: "Pistachio Gelato Sundae",
    madeByCreator: "Sarah Jenkins",
    time: 10,
    isFavorite: false,
    difficulty: "Easy",
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=1200",
    category: "Desserts",
    ingredients: [
      { quantity: 3, unit: "scoops", name: "pistachio gelato" },
      { quantity: 2, unit: "tbsp", name: "crushed roasted pistachios" },
      { quantity: 2, unit: "tbsp", name: "whipped cream" },
      { quantity: 1, unit: "tbsp", name: "dark chocolate sauce" },
      { quantity: 1, unit: "waffle", name: "wedge" },
    ],
    instructions: [
      "Scoop pistachio gelato into a serving glass or bowl.",
      "Top with a generous swirl of fresh whipped cream.",
      "Drizzle dark chocolate sauce over top.",
      "Sprinkle crushed roasted pistachios and insert a waffle wedge.",
    ],
  },
  {
    id: "rec-036",
    foodName: "Pan-Seared Salmon with Asparagus",
    madeByCreator: "Chef Elena Rostova",
    time: 20,
    isFavorite: false,
    difficulty: "Medium",
    image:
      "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=1200",
    category: "Main",
    ingredients: [
      { quantity: 2, unit: "", name: "salmon fillets, skin-on" },
      { quantity: 1, unit: "bunch", name: "fresh asparagus, trimmed" },
      { quantity: 2, unit: "tbsp", name: "olive oil" },
      { quantity: 2, unit: "tbsp", name: "butter" },
      { quantity: 1, unit: "", name: "lemon, sliced" },
      { quantity: 0, unit: "", name: "Salt and pepper to taste" },
    ],
    instructions: [
      "Pat salmon skin dry and season both sides with salt and pepper.",
      "Heat olive oil in a skillet over high heat; place salmon skin-side down.",
      "Cook for 4 minutes until skin is crispy, then flip and add butter and lemon slices.",
      "Add asparagus to the same pan and sear for 3–4 minutes until tender-crisp.",
    ],
  },
  {
    id: "rec-037",
    foodName: "Fluffy Belgian Waffles",
    madeByCreator: "Marcus Vance",
    time: 20,
    isFavorite: false,
    difficulty: "Easy",
    image: "https://images.unsplash.com/photo-1562376552-0d160a2f238d?w=1200",
    category: "Breakfast",
    ingredients: [
      { quantity: 2, unit: "cups", name: "flour" },
      { quantity: 2, unit: "tbsp", name: "sugar" },
      { quantity: 1, unit: "tbsp", name: "baking powder" },
      { quantity: 2, unit: "", name: "eggs, separated" },
      { quantity: 1.5, unit: "cups", name: "milk" },
      { quantity: 0.5, unit: "cup", name: "melted butter" },
      { quantity: 0, unit: "", name: "Maple syrup and butter for serving" },
    ],
    instructions: [
      "Mix flour, sugar, baking powder, egg yolks, milk, and melted butter into a batter.",
      "Whip egg whites in a separate bowl until stiff peaks form.",
      "Gently fold whipped whites into the batter.",
      "Pour into a preheated waffle iron and cook until golden brown and crisp.",
    ],
  },
  {
    id: "rec-038",
    foodName: "Tropical Mango Passionfruit Smoothie",
    madeByCreator: "Kenji Takahashi",
    time: 5,
    isFavorite: false,
    difficulty: "Easy",
    image: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=1200",
    category: "Drinks",
    ingredients: [
      { quantity: 1, unit: "cup", name: "frozen mango chunks" },
      { quantity: 0.5, unit: "cup", name: "passionfruit juice" },
      { quantity: 0.5, unit: "cup", name: "Greek yogurt" },
      { quantity: 0.5, unit: "cup", name: "orange juice" },
      { quantity: 1, unit: "tbsp", name: "chia seeds" },
    ],
    instructions: [
      "Combine frozen mango, passionfruit juice, Greek yogurt, and orange juice in a blender.",
      "Blend on high speed until completely smooth.",
      "Pour into a tall glass and stir in chia seeds.",
    ],
  },
  {
    id: "rec-039",
    foodName: "Strawberry Shortcake",
    madeByCreator: "Sarah Jenkins",
    time: 35,
    isFavorite: false,
    difficulty: "Medium",
    image:
      "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=1200",
    category: "Desserts",
    ingredients: [
      { quantity: 2, unit: "cups", name: "all-purpose flour" },
      { quantity: 0.25, unit: "cup", name: "sugar" },
      { quantity: 1, unit: "tbsp", name: "baking powder" },
      { quantity: 0.5, unit: "cup", name: "cold butter, cubed" },
      { quantity: 2, unit: "cups", name: "fresh strawberries, sliced" },
      { quantity: 1, unit: "cup", name: "heavy whipping cream" },
      { quantity: 1, unit: "tsp", name: "vanilla extract" },
    ],
    instructions: [
      "Macerate strawberries in 1 tbsp sugar for 20 minutes.",
      "Cut cold butter into flour, baking powder, and sugar until crumbly; add 1/2 cup cream to form biscuits.",
      "Bake biscuit rounds at 400°F (200°C) for 15 minutes.",
      "Whip remaining cream with vanilla; split biscuits and layer with strawberries and cream.",
    ],
  },
  {
    id: "rec-040",
    foodName: "Artisanal Beef Burger",
    madeByCreator: "Marcus Vance",
    time: 20,
    isFavorite: false,
    difficulty: "Easy",
    image:
      "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=1200",
    category: "Main",
    ingredients: [
      { quantity: 0.5, unit: "lb", name: "ground chuck beef (80/20)" },
      { quantity: 1, unit: "", name: "brioche bun, toasted" },
      { quantity: 1, unit: "slice", name: "cheddar cheese" },
      { quantity: 2, unit: "slices", name: "ripe tomato" },
      { quantity: 1, unit: "leaf", name: "butter lettuce" },
      { quantity: 2, unit: "tbsp", name: "burger sauce" },
      { quantity: 0, unit: "", name: "Salt and pepper" },
    ],
    instructions: [
      "Form beef into a patty and season generously with salt and pepper.",
      "Sear in a hot cast-iron skillet for 3 minutes per side.",
      "Top with cheddar cheese during the last minute and cover pan to melt.",
      "Assemble burger on toasted brioche bun with sauce, lettuce, and tomato.",
    ],
  },
  {
    id: "rec-041",
    foodName: "Classic Lemon Blueberry Scones",
    madeByCreator: "Chef Elena Rostova",
    time: 30,
    isFavorite: false,
    difficulty: "Medium",
    image:
      "https://images.unsplash.com/photo-1589119908995-c6837fa14848?w=1200",
    category: "Breakfast",
    ingredients: [
      { quantity: 2, unit: "cups", name: "flour" },
      { quantity: 0.33, unit: "cup", name: "sugar" },
      { quantity: 1, unit: "tbsp", name: "lemon zest" },
      { quantity: 0.5, unit: "cup", name: "cold unsalted butter" },
      { quantity: 0.5, unit: "cup", name: "heavy cream" },
      { quantity: 1, unit: "cup", name: "fresh blueberries" },
      { quantity: 1, unit: "tbsp", name: "lemon juice" },
    ],
    instructions: [
      "Pulse flour, sugar, lemon zest, and cold butter until coarse crumbs form.",
      "Fold in heavy cream and fresh blueberries until dough holds together.",
      "Shape into a disc, slice into 8 wedges, and bake at 400°F (200°C) for 18 minutes.",
      "Drizzle with a quick glaze made from lemon juice and powdered sugar.",
    ],
  },
  {
    id: "rec-042",
    foodName: "Creamy Pumpkin Spice Latte",
    madeByCreator: "Kenji Takahashi",
    time: 10,
    isFavorite: false,
    difficulty: "Easy",
    image:
      "https://images.unsplash.com/photo-1507133750040-4a8f57021571?w=1200",
    category: "Drinks",
    ingredients: [
      { quantity: 2, unit: "shots", name: "espresso" },
      { quantity: 1, unit: "cup", name: "milk" },
      { quantity: 2, unit: "tbsp", name: "pumpkin puree" },
      { quantity: 1, unit: "tbsp", name: "maple syrup" },
      { quantity: 0.5, unit: "tsp", name: "pumpkin pie spice" },
      { quantity: 0, unit: "", name: "Whipped cream for topping" },
    ],
    instructions: [
      "Whisk milk, pumpkin puree, maple syrup, and spice in a saucepan over medium heat until warm.",
      "Froth milk mixture with a handheld frother.",
      "Pour hot espresso into a mug and top with frothed pumpkin milk.",
      "Garnish with whipped cream and a dusting of spice.",
    ],
  },
  {
    id: "rec-043",
    foodName: "Chilled Mango Sago Dessert",
    madeByCreator: "Kenji Takahashi",
    time: 25,
    isFavorite: false,
    difficulty: "Easy",
    image:
      "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=1200",
    category: "Desserts",
    ingredients: [
      { quantity: 0.5, unit: "cup", name: "small sago (tapioca pearls)" },
      { quantity: 2, unit: "", name: "ripe mangoes, diced" },
      { quantity: 1, unit: "cup", name: "coconut milk" },
      { quantity: 0.5, unit: "cup", name: "evaporated milk" },
      { quantity: 2, unit: "tbsp", name: "condensed milk" },
    ],
    instructions: [
      "Boil tapioca pearls in water for 10 minutes until translucent; drain and rinse with cold water.",
      "Blend half of diced mango with coconut milk and condensed milk until smooth.",
      "Mix blended mango with tapioca pearls and evaporated milk in a bowl.",
      "Top with remaining fresh mango cubes and chill before serving.",
    ],
  },
  {
    id: "rec-044",
    foodName: "Classic Pad Thai",
    madeByCreator: "Marcus Vance",
    time: 30,
    isFavorite: false,
    difficulty: "Medium",
    image: "https://images.unsplash.com/photo-1559847844-5315695dadae?w=1200",
    category: "Main",
    ingredients: [
      { quantity: 8, unit: "oz", name: "flat rice noodles" },
      { quantity: 2, unit: "tbsp", name: "tamarind paste" },
      { quantity: 2, unit: "tbsp", name: "fish sauce" },
      { quantity: 1, unit: "tbsp", name: "palm sugar" },
      { quantity: 0.5, unit: "lb", name: "shrimp or chicken" },
      { quantity: 2, unit: "", name: "eggs, lightly beaten" },
      { quantity: 1, unit: "cup", name: "bean sprouts" },
      { quantity: 0.25, unit: "cup", name: "crushed peanuts" },
    ],
    instructions: [
      "Soak rice noodles in warm water for 20 minutes until softened.",
      "Whisk tamarind paste, fish sauce, and sugar in a small bowl for the sauce.",
      "Stir-fry shrimp in a hot wok, push aside, and scramble eggs in the pan.",
      "Add drained noodles and sauce; toss for 3 minutes until noodles absorb sauce.",
      "Garnish with bean sprouts and crushed peanuts.",
    ],
  },
  {
    id: "rec-045",
    foodName: "Fresh Berry Tartlets",
    madeByCreator: "Sarah Jenkins",
    time: 45,
    isFavorite: false,
    difficulty: "Medium",
    image:
      "https://images.unsplash.com/photo-1568571780765-9276ac8b75a2?w=1200",
    category: "Desserts",
    ingredients: [
      { quantity: 6, unit: "mini", name: "pre-baked pastry shells" },
      { quantity: 1, unit: "cup", name: "pastry cream or vanilla pudding" },
      { quantity: 0.5, unit: "cup", name: "fresh raspberries" },
      { quantity: 0.5, unit: "cup", name: "fresh blueberries" },
      { quantity: 2, unit: "tbsp", name: "apricot jam (for glaze)" },
    ],
    instructions: [
      "Spoon room-temperature pastry cream evenly into pastry shells.",
      "Arrange fresh raspberries and blueberries decorative on top.",
      "Warm apricot jam with 1 tsp water and brush lightly over fruit for a glossy finish.",
      "Chill for 30 minutes before serving.",
    ],
  },
  {
    id: "rec-046",
    foodName: "Crispy Omelette with Herbs and Cheese",
    madeByCreator: "Chef Elena Rostova",
    time: 10,
    isFavorite: false,
    difficulty: "Easy",
    image:
      "https://images.unsplash.com/photo-1510693206972-df098062cb71?w=1200",
    category: "Breakfast",
    ingredients: [
      { quantity: 3, unit: "large", name: "eggs" },
      { quantity: 1, unit: "tbsp", name: "butter" },
      { quantity: 2, unit: "tbsp", name: "fresh chives, finely chopped" },
      { quantity: 0.25, unit: "cup", name: "shredded Gruyère cheese" },
      { quantity: 0, unit: "", name: "Salt and white pepper" },
    ],
    instructions: [
      "Whisk eggs vigorously with salt and pepper until frothy.",
      "Melt butter in a non-stick skillet over medium-low heat.",
      "Pour eggs into skillet and swirl pan to spread evenly.",
      "When eggs begin to set, sprinkle cheese and fresh chives down the center.",
      "Fold omelette neatly and slide onto plate.",
    ],
  },
  {
    id: "rec-047",
    foodName: "Iced Green Tea Lemonade",
    madeByCreator: "Kenji Takahashi",
    time: 5,
    isFavorite: false,
    difficulty: "Easy",
    image:
      "https://images.unsplash.com/photo-1499638673689-79a0b5115d87?w=1200",
    category: "Drinks",
    ingredients: [
      { quantity: 1, unit: "cup", name: "brewed green tea, chilled" },
      { quantity: 0.5, unit: "cup", name: "fresh lemonade" },
      { quantity: 1, unit: "tbsp", name: "simple syrup" },
      { quantity: 0, unit: "", name: "Mint leaves for garnish" },
      { quantity: 0, unit: "", name: "Ice cubes" },
    ],
    instructions: [
      "Fill a tall glass to the top with ice cubes.",
      "Pour chilled green tea and fresh lemonade over ice.",
      "Add simple syrup and stir thoroughly.",
      "Garnish with fresh mint leaves and a lemon wheel.",
    ],
  },
  {
    id: "rec-048",
    foodName: "Creamy Tomato Basil Soup",
    madeByCreator: "Chef Elena Rostova",
    time: 30,
    isFavorite: false,
    difficulty: "Easy",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=1200",
    category: "Main",
    ingredients: [
      {
        quantity: 1,
        unit: "can (28 oz)",
        name: "whole peeled San Marzano tomatoes",
      },
      { quantity: 0.5, unit: "cup", name: "heavy cream" },
      { quantity: 1, unit: "cup", name: "vegetable broth" },
      { quantity: 0.5, unit: "cup", name: "fresh basil leaves" },
      { quantity: 1, unit: "small", name: "onion, diced" },
      { quantity: 2, unit: "tbsp", name: "butter" },
    ],
    instructions: [
      "Melt butter in a pot and sauté onion until translucent.",
      "Add canned tomatoes and vegetable broth; simmer for 20 minutes.",
      "Add fresh basil leaves and blend soup with an immersion blender until smooth.",
      "Stir in heavy cream, season with salt and pepper, and warm gently.",
    ],
  },
  {
    id: "rec-049",
    foodName: "Sparkling Peach Mint Spritzer",
    madeByCreator: "Kenji Takahashi",
    time: 5,
    isFavorite: false,
    difficulty: "Easy",
    image:
      "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=1200",
    category: "Drinks",
    ingredients: [
      { quantity: 0.5, unit: "cup", name: "fresh peach puree" },
      { quantity: 6, unit: "fresh", name: "mint leaves" },
      { quantity: 1, unit: "tbsp", name: "lime juice" },
      { quantity: 1, unit: "cup", name: "sparkling water" },
      { quantity: 1, unit: "tbsp", name: "simple syrup" },
      { quantity: 0, unit: "", name: "Ice cubes" },
    ],
    instructions: [
      "Muddle mint leaves and lime juice at the bottom of a tall glass.",
      "Add peach puree, simple syrup, and fill glass with ice cubes.",
      "Top off with sparkling water and stir gently before serving.",
    ],
  },
  {
    id: "rec-050",
    foodName: "Classic New York Cheesecake",
    madeByCreator: "Sarah Jenkins",
    time: 75,
    isFavorite: false,
    difficulty: "Hard",
    image:
      "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=1200",
    category: "Desserts",
    ingredients: [
      { quantity: 1.5, unit: "cups", name: "graham cracker crumbs" },
      { quantity: 3, unit: "tbsp", name: "melted butter" },
      { quantity: 24, unit: "oz", name: "cream cheese, softened" },
      { quantity: 1, unit: "cup", name: "granulated sugar" },
      { quantity: 3, unit: "large", name: "eggs" },
      { quantity: 0.33, unit: "cup", name: "sour cream" },
      { quantity: 1, unit: "tsp", name: "vanilla extract" },
    ],
    instructions: [
      "Press graham cracker crumbs and melted butter into the bottom of a 9-inch springform pan.",
      "Beat cream cheese and sugar until smooth, then mix in eggs one at a time.",
      "Fold in sour cream and vanilla extract, then pour over crust.",
      "Bake at 325°F (165°C) for 55 minutes, then chill in refrigerator for 6 hours.",
    ],
  },
  {
    id: "rec-051",
    foodName: "Warm Apple Cinnamon Galette",
    madeByCreator: "Sarah Jenkins",
    time: 50,
    isFavorite: false,
    difficulty: "Medium",
    image:
      "https://images.unsplash.com/photo-1568571780765-9276ac8b75a2?w=1200",
    category: "Desserts",
    ingredients: [
      { quantity: 1, unit: "sheet", name: "pie crust dough" },
      { quantity: 2, unit: "", name: "Honeycrisp apples, thinly sliced" },
      { quantity: 2, unit: "tbsp", name: "brown sugar" },
      { quantity: 1, unit: "tsp", name: "ground cinnamon" },
      { quantity: 1, unit: "tbsp", name: "butter, cubed" },
      { quantity: 1, unit: "", name: "egg (for egg wash)" },
    ],
    instructions: [
      "Roll out pie crust onto a parchment-lined baking sheet.",
      "Toss sliced apples with brown sugar and ground cinnamon.",
      "Arrange apple slices in center of crust, leaving a 2-inch border.",
      "Fold edges of crust over apples, dot with butter, and brush edges with egg wash.",
      "Bake at 375°F (190°C) for 35 minutes until golden.",
    ],
  },
  {
    id: "rec-052",
    foodName: "Savory Breakfast Burrito",
    madeByCreator: "Chef Elena Rostova",
    time: 15,
    isFavorite: false,
    difficulty: "Easy",
    image:
      "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=1200",
    category: "Breakfast",
    ingredients: [
      { quantity: 1, unit: "large", name: "flour tortilla" },
      { quantity: 2, unit: "large", name: "eggs, scrambled" },
      { quantity: 2, unit: "strips", name: "bacon, cooked and chopped" },
      { quantity: 0.25, unit: "cup", name: "shredded cheddar cheese" },
      { quantity: 0.25, unit: "cup", name: "diced avocado" },
      { quantity: 2, unit: "tbsp", name: "salsa" },
    ],
    instructions: [
      "Warm flour tortilla on a skillet for 30 seconds per side.",
      "Layer scrambled eggs, chopped bacon, shredded cheddar, and avocado in center.",
      "Top with salsa, fold sides inward, and roll tightly into a burrito.",
      "Sear wrapped burrito on hot skillet for 1 minute per side until crisp.",
    ],
  },
];

export default data;
